# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"firstName" VARCHAR,"lastName" VARCHAR,"userName" VARCHAR NOT NULL,"identityId" VARCHAR NOT NULL);

# --- !Downs

drop table "USER";

